# Site wide configuration

title: "UCPC 2019"
description: "우리 1년 더 한다."
# if you modify locale please have a look at _data/messages.yml too
locale: en
# for meta name="author" :
author:

# Target date in UTC / GMT
countdown:
  theme: red
  year: 2019
  month: 7
  day: 20
  hour: 10
  minute: 0

# Site owner
owner:
  name: 전국 대학생 프로그래밍 대회 동아리 연합
  homepage: https://www.facebook.com/groups/250186671672125/
  email: ucpc.kr@gmail.com
  twitter:
  google_plus:
  instagram:
  facebook:

# Jekyll configuration
sass:
  sass_dir: _sass
  style: compressed
permalink:
kramdown:
  toc_levels: 1..2
highlighter: rouge


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
